version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: mcp-test-postgres
    environment:
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: mcp123
      POSTGRES_DB: mcp-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: mcp-test-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mcp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 